### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'register_scene'

### ISSUE THREAD

**Issue by VulcanRav** [peterbrittain/asciimatics#100]
I am struggling in understanding asciimatics (got to admit I'm rather new to programming in general), but I read the documentation and definitions in the source code.

When I try to create a simple scene containing a single frame (which to my understanding is an effect subclass) I get this error:

```
Traceback (most recent call last):
  File "hello.py", line 20, in <module>
    Screen.wrapper(demo)
  
File "/usr/local/lib/python3.5/dist-packages/asciimatics/screen.py", line 1023, in wrapper
    func(screen)
  
File "hello.py", line 15, in demo
    Scene([my_frame], -1, name = "MainFrame")
  
File "/usr/local/lib/python3.5/dist-packages/asciimatics/scene.py", line 26, in __init__
    self.add_effect(effect)
  
File "/usr/local/lib/python3.5/dist-packages/asciimatics/scene.py", line 72, in add_effect
    effect.register_scene(self)
AttributeError: 'NoneType' object has no attribute 'register_scene'
`
```

This is my hello.py file:

```
from asciimatics.widgets import Frame, Button, Layout
from asciimatics.scene import Scene

def demo(screen):
    def button_click():
        pass

    my_layout = Layout([1], fill_frame=True)
    my_frame = Frame(screen, 100, 100, has_border=False).add_layout(my_layout)
    my_widget = Button("Gimme some text", button_click)
    my_layout.add_widget(my_widget, 0)
    
    scenes = [
        Scene([my_frame], -1, name="MainFrame")
    ]

    screen.play(scenes, start_scene=0)

Screen.wrapper(demo)
```

**Comment by peterbrittain** [comment]
A few bugs I can see.  I might have missed something, but try this instead...

```
from asciimatics.widgets import Frame, Button, Layout
from asciimatics.scene import Scene

def demo(screen):
    def button_click():
        pass

    my_layout = Layout([1], fill_frame=True)
    my_frame = Frame(screen, 100, 100, has_border=False)
    my_frame.add_layout(my_layout)
    my_widget = Button("Gimme some text", button_click)
    my_layout.add_widget(my_widget, 0)
    my_frame.fix()
    
    scenes = [
        Scene([my_frame], -1, name="MainFrame")
    ]

    screen.play(scenes)

Screen.wrapper(demo)
```

**Comment by peterbrittain** [comment]
Just tried running the above and it works for me.

**Comment by VulcanRav** [comment]
Thank you, still a bit confused on why changing the order (creating the layout before the frame and adding the layout to the frame later, same for the widget) raises errors.

**Comment by peterbrittain** [comment]
The main bug was that `add_layout()` doesn't return a Frame and so you were using `None` instead of a Frame object.
