### ISSUE TITLE
Unable to build with setup tools

### ISSUE THREAD

**Issue by mroutis** [peterbrittain/asciimatics#181]
**Describe the bug**
I'm trying to install `asciimatics` with setuptools (eg. `python setup.py install...`) and it's throwing me an error.

```
Traceback (most recent call last):
  File "setup.py", line 78, in <module>
    test_suite='nose.collector',
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 370, in __init__
    k: v for k, v in attrs.items()
  File "/usr/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 529, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/mroutis/tmp/asciimatics-1.10.0/.eggs/setuptools_scm-3.1.0-py3.7.egg/setuptools_scm/integration.py", line 23, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/home/mroutis/tmp/asciimatics-1.10.0/.eggs/setuptools_scm-3.1.0-py3.7.egg/setuptools_scm/__init__.py", line 142, in get_version
    parsed_version = _do_parse(config)
  File "/home/mroutis/tmp/asciimatics-1.10.0/.eggs/setuptools_scm-3.1.0-py3.7.egg/setuptools_scm/__init__.py", line 111, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/home/mroutis/tmp/asciimatics-1.10.0'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

**To Reproduce**
```bash
wget 'https://github.com/peterbrittain/asciimatics/archive/1.10.0.tar.gz'
tar xvfz 1.10.0.tar.gz
cd asciimatics-1.10.0
python setup.py --version
```

**Expected behavior**
Returns the version when running `python setup.py --version`:

```
1.10.0
```

**Screenshots**
![2018-10-17-09 42 39](https://user-images.githubusercontent.com/7363250/47094581-171e8600-d1f1-11e8-91a2-4b60c23387d2.png)

**System details (please complete the following information):**
 - OS: Arch Linux
- Kernel: x86_64 Linux 4.18.14-arch1-1-ARCH
 - Asciimatics version: 1.10.0
- Setup tools version: 40.4.3

**Additional context**
If I specify the version inside the setup() function with `version: 1.10.0`, instead of line: https://github.com/peterbrittain/asciimatics/blob/master/setup.py#L30 it works.

**Comment by Eeems** [comment]
The error leads me to believe that you should be doing a git clone instead of downloading and extracting the tarball.

**Comment by peterbrittain** [comment]
Like the error says, you can't use `setuptools_scm` (which is what we use for our version numbering) with a tarball.  This should work for you instead:

```
git clone https://github.com/peterbrittain/asciimatics.git
cd asciimatics
git checkout v1.10
python setup.py --version
```

**Comment by mroutis** [comment]
Thanks, @Eeems, @peterbrittain!
