### ISSUE TITLE
Asciimatics ModuleNotFoundError

### ISSUE THREAD

**Issue by heavyblack1** [peterbrittain/asciimatics#219]
Hello i want learn how to use asciimatics and every time i try demo code python says aciimatics don't contain screen and other modules yes i have asciimatics installed   

# my setup
asciimatics 1.11.0 
windows 10 build 1809

> python 3.7
>  pip install asciimatics

ubuntu 18.04

> python 3.6
> pip3 install asciimatics

# What i try
```python
from asciimatics.effects import Cycle, Stars
from asciimatics.renderers import FigletText
from asciimatics.scene import Scene
from asciimatics.screen import Screen

def demo(screen):
    effects = [
        Cycle(
            screen,
            FigletText("ASCIIMATICS", font='big'),
            int(screen.height / 2 - 8)),
        Cycle(
            screen,
            FigletText("ROCKS!", font='big'),
            int(screen.height / 2 + 3)),
        Stars(screen, 200)
    ]
    screen.play([Scene(effects, 500)])

Screen.wrapper(demo)
```

# traceback
on ubuntu and windows
```python
Traceback (most recent call last):
  File "asciimatics.py", line 1, in <module>
    from asciimatics.effects import Cycle, Stars
  File "/home/theavyblack/asciimatics.py", line 1, in <module>
    from asciimatics.effects import Cycle, Stars
ModuleNotFoundError: No module named 'asciimatics.effects'; 'asciimatics' is not a package

```

**Comment by peterbrittain** [comment]
That's going to be some bug in the system install.  I suggest you run `pip -V` to find where it is installing its packages and then run the following commands to check your python path:
```
python
import sys
sys.path
```
This should show you where your python interpreter is looking for packages.  If the list from python doesn't contain your path used by pip, that is your problem.  You are either using the wrong python interpreter (e.g. a different version of python from the one used to insall pip) or something is messing around with your interpreter imoprt path.

**Comment by heavyblack1** [comment]
I tried and i don't see anything wrong
installed version
pip3 -V
> pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
python3 -V
> Python 3.6.8
whean i try unintall is showed is in this location in my opinion is in right place
/home/heavyblack/.local/lib/python3.6/site-packages/asciimatics/exceptions.py

output of sys.path
```
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/tomas/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']
```
and i installed again
```
pip3 install asciimatics
Collecting asciimatics
  Using cached https://files.pythonhosted.org/packages/4a/cf/2cf9843608b2d6ee178a04860600b63b4db55a6746adfa46d73cbcd85a7d/asciimatics-1.11.0-py2.py3-none-any.whl
Collecting Pillow>=2.7.0 (from asciimatics)
  Using cached https://files.pythonhosted.org/packages/14/41/db6dec65ddbc176a59b89485e8cc136a433ed9c6397b6bfe2cd38412051e/Pillow-6.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyfiglet>=0.7.2 (from asciimatics)
  Using cached https://files.pythonhosted.org/packages/33/07/fcfdd7a2872f5b348953de35acce1544dab0c1e8368dca54279b1cde5c15/pyfiglet-0.8.post1-py2.py3-none-any.whl
Collecting wcwidth (from asciimatics)
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting future (from asciimatics)
Installing collected packages: Pillow, pyfiglet, wcwidth, future, asciimatics
Successfully installed Pillow-6.1.0 asciimatics-1.11.0 future-0.17.1 pyfiglet-0.8.post1 wcwidth-0.1.7

```

same on windows 
```
PS C:\Users\heavyblack> pip -V
pip 19.1.1 from c:\python37\lib\site-packages\pip (python 3.7)
PS C:\Users\heavyblack> python -V
Python 3.7.3
PS C:\Users\heavyblack>

sys.path
['', 'C:\\Python37\\python37.zip', 'C:\\Python37\\DLLs', 'C:\\Python37\\lib', 'C:\\Python37', 'C:\\Users\\heavyblack\\AppData\\Roaming\\Python\\Python37\\site-packages', 'C:\\Python37\\lib\\site-packages', 'C:\\Python37\\lib\\site-packages\\py_curses_editor-1.2.1-py3.7.egg', 'C:\\Python37\\lib\\site-packages\\win32', 'C:\\Python37\\lib\\site-packages\\win32\\lib', 'C:\\Python37\\lib\\site-packages\\Pythonwin']

PS C:\Users\heavyblack> python -m site
sys.path = [
    'C:\\Users\\heavyblack',
    'C:\\Python37\\python37.zip',
    'C:\\Python37\\DLLs',
    'C:\\Python37\\lib',
    'C:\\Python37',
    'C:\\Users\\heavyblack\\AppData\\Roaming\\Python\\Python37\\site-packages',
    'C:\\Python37\\lib\\site-packages',
    'C:\\Python37\\lib\\site-packages\\py_curses_editor-1.2.1-py3.7.egg',
    'C:\\Python37\\lib\\site-packages\\win32',
    'C:\\Python37\\lib\\site-packages\\win32\\lib',
    'C:\\Python37\\lib\\site-packages\\Pythonwin',
]
USER_BASE: 'C:\\Users\\heavyblack\\AppData\\Roaming\\Python' (exists)
USER_SITE: 'C:\\Users\\heavyblack\\AppData\\Roaming\\Python\\Python37\\site-packages' (exists)
ENABLE_USER_SITE: True
```

**Comment by peterbrittain** [comment]
I notice that you have a different user (heavyblack vs tomas) in the linux sys.path from the one where you installed/uninstalled asciimatics.  Seems a likely culprit there.

Windows beats me!  I can't see how its anything to do with asciimatics, though, because all it does is a standard package setup.  Where exactly is asciimatics installed in this case?

**Comment by peterbrittain** [comment]
I'm assuming that tracking down exact paths solved your issue.

**Comment by heavyblack1** [comment]
no i don't solve issue i'm stuck
in tomas profile is everything right

and i tried copy asciimatics lib folder in my project folder and work this mean python can't find    `/home/tomas/.local/lib/python3.6/site-packages/asciimatics/`

```
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/tomas/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']





home/tomas/.local/lib/python3.6/site-packages/asciimatics/effects.py
  /home/tomas/.local/lib/python3.6/site-packages/asciimatics/event.py
  
  /home/tomas/.local/lib/python3.6/site-packages/asciimatics/particles.py
  /home/tomas/.local/lib/python3.6/site-packages/asciimatics/paths.py
  /home/tomas/.local/lib/python3.6/site-packages/asciimatics/renderers.py
  /home/tomas/.local/lib/python3.6/site-packages/asciimatics/scene.py
  /home/tomas/.local/lib/python3.6/site-packages/asciimatics/screen.py
  /home/tomas/.local/lib/python3.6/site-packages/asciimatics/sprites.py
  /home/tomas/.local/lib/python3.6/site-packages/asciimatics/utilities.py
  /home/tomas/.local/lib/python3.6/site-packages/asciimatics/version.py
  /home/tomas/.local/lib/python3.6/site-packages/asciimatics/widgets.py

```

**Comment by peterbrittain** [comment]
I'm afraid I can't help.  This is nothing to do with the package (which I have just installed from pypi with pip).

My last guess is that you are running in a directory that contains an `asciimatics` file or directory.  Python will use that file/directory over installed packages.

**Comment by heavyblack1** [comment]
Thanks problem is i named my script as `asciimatics.py`

**Comment by peterbrittain** [comment]
Yeah - that would do it!  You don't want to use names that clash with packages...  Glad we got to the bottom of it.
