### ISSUE TITLE
Cannot run most samples due to issue with future

### ISSUE THREAD

**Issue by PiggyClone205** [peterbrittain/asciimatics#258]
**Describe the bug**
I cannot run most of the sample programs, as they all result in a similar result to the traceback below.

**To Reproduce**
1. Run samples that utilize asciimatics.widgets or asciimatics.effects.

**Expected behavior**
I expected the sample programs provided to correctly run.

**Screenshots**
Traceback (most recent call last):
  File "pyGraphicRPG.py", line 3, in <module>
    from asciimatics.widgets import Frame, ListBox, Layout, Divider, Text, \
  File "C:\Users\jdgda\AppData\Local\Programs\Python\Python38-32\lib\site-packages\asciimatics\widgets.py", line 20, in <module>
    from future.moves.itertools import zip_longest
ModuleNotFoundError: No module named 'future.moves.itertools'

**System details (please complete the following information):**
 - OS Version: Windows 10
 - Asciimatics version: 1.11.0

**Comment by PiggyClone205** [comment]
Just realized that my python install is apparently ruined, as other modules in my own project are broken. Closing because you will likely be unable to reproduce.

**Comment by PiggyClone205** [comment]
Issue was resolved by reinstalling future for anyone who finds this issue with the same problem.
