### ISSUE TITLE
ZeroDivisionError on scroll bar position calculation

### ISSUE THREAD

**Issue by oldium** [peterbrittain/asciimatics#59]
Example forms.py on Windows 10 (Anniversary Update), just resize the window height, so that the condition _max_height - _canvas.height is 0.

```
Traceback (most recent call last):
  File "forms.py", line 131, in <module>
    Screen.wrapper(demo, catch_interrupt=False, arguments=[last_scene])
  File "C:\Python36\lib\site-packages\asciimatics\screen.py", line 998, in wrapper
    func(screen, *arguments)
  File "main.py", line 126, in demo
    screen.play(scenes, stop_on_resize=True, start_scene=scene)
  File "C:\Python36\lib\site-packages\asciimatics\screen.py", line 1141, in play
    self.draw_next_frame(repeat=repeat)
  File "C:\Python36\lib\site-packages\asciimatics\screen.py", line 1237, in draw_next_frame
    effect.update(self._frame)
  File "C:\Python36\lib\site-packages\asciimatics\effects.py", line 65, in update
    self._update(frame_no)
  File "C:\Python36\lib\site-packages\asciimatics\widgets.py", line 299, in _update
    (self._max_height - self._canvas.height))
ZeroDivisionError: division by zero
```

**Comment by peterbrittain** [comment]
Nice catch.  Now fixed in https://github.com/peterbrittain/asciimatics/commit/1e3093f02f3ee5a488b22101534f391d86952d2d
