### ISSUE TITLE
Import Error - InvalidFields 

### ISSUE THREAD

**Issue by frakman1** [peterbrittain/asciimatics#63]
```
 c:\Python27\asciimatics_test\asciimatics\samples>python forms.py
 Traceback (most recent call last):
   File "forms.py", line 8, in <module>
     from asciimatics.exceptions import ResizeScreenError, NextScene, StopApplication, \
 ImportError: cannot import name InvalidFields

``` 

 Running on windows 7
` Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)] on win32
` 

Installed via `pip install asciimatics`

**Comment by peterbrittain** [comment]
You have a version mismatch.

InvalidFields is only in the master branch of asciimatics right now.  You are running the latest samples against an older (v1.7) version of asciimatics.

Try running the same code from the v1.7 branch: https://github.com/peterbrittain/asciimatics/tree/v1.7/samples

**Comment by frakman1** [comment]
Thank you. I did a `pip uninstall asciimatics` followed by a `git pull` and a `git checkout v1.7` then a `python setup.py install` and tried again. Although forms.py now works, I can't get some others to work. 
pacman.py:
```
c:\Python27\asciimatics_test\asciimatics\samples>python pacman.py
Traceback (most recent call last):
  File "pacman.py", line 533, in <module>
    Screen.wrapper(demo)
  File "build\bdist.win32\egg\asciimatics\screen.py", line 1000, in wrapper
  File "pacman.py", line 464, in demo
    ColourImageFile(screen, "pacman.png", 16, 0, True),
  File "build\bdist.win32\egg\asciimatics\renderers.py", line 373, in __init__
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 512, in __getattr__
    raise AttributeError(name)
AttributeError: __exit__
```
images.py:
```
c:\Python27\asciimatics_test\asciimatics\samples>python images.py
Traceback (most recent call last):
  File "images.py", line 40, in <module>
    Screen.wrapper(demo)
  File "build\bdist.win32\egg\asciimatics\screen.py", line 1000, in wrapper
  File "images.py", line 14, in demo
    screen.height-2), 0,
  File "build\bdist.win32\egg\asciimatics\renderers.py", line 373, in __init__
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 512, in __getattr__
    raise AttributeError(name)
AttributeError: __exit__
```



If it's any help, here is the install log too:
```
$ python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to asciimatics.egg-info\requires.txt
writing asciimatics.egg-info\PKG-INFO
writing top-level names to asciimatics.egg-info\top_level.txt
writing dependency_links to asciimatics.egg-info\dependency_links.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'asciimatics.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
copying asciimatics\exceptions.py -> build\lib\asciimatics
copying asciimatics\renderers.py -> build\lib\asciimatics
copying asciimatics\screen.py -> build\lib\asciimatics
copying asciimatics\version.py -> build\lib\asciimatics
copying asciimatics\widgets.py -> build\lib\asciimatics
creating build\bdist.win32\egg
creating build\bdist.win32\egg\asciimatics
copying build\lib\asciimatics\effects.py -> build\bdist.win32\egg\asciimatics
copying build\lib\asciimatics\event.py -> build\bdist.win32\egg\asciimatics
copying build\lib\asciimatics\exceptions.py -> build\bdist.win32\egg\asciimatics
copying build\lib\asciimatics\particles.py -> build\bdist.win32\egg\asciimatics
copying build\lib\asciimatics\paths.py -> build\bdist.win32\egg\asciimatics
copying build\lib\asciimatics\renderers.py -> build\bdist.win32\egg\asciimatics
copying build\lib\asciimatics\scene.py -> build\bdist.win32\egg\asciimatics
copying build\lib\asciimatics\screen.py -> build\bdist.win32\egg\asciimatics
copying build\lib\asciimatics\sprites.py -> build\bdist.win32\egg\asciimatics
copying build\lib\asciimatics\version.py -> build\bdist.win32\egg\asciimatics
copying build\lib\asciimatics\widgets.py -> build\bdist.win32\egg\asciimatics
copying build\lib\asciimatics\__init__.py -> build\bdist.win32\egg\asciimatics
byte-compiling build\bdist.win32\egg\asciimatics\effects.py to effects.pyc
byte-compiling build\bdist.win32\egg\asciimatics\event.py to event.pyc
byte-compiling build\bdist.win32\egg\asciimatics\exceptions.py to exceptions.pyc
byte-compiling build\bdist.win32\egg\asciimatics\particles.py to particles.pyc
byte-compiling build\bdist.win32\egg\asciimatics\paths.py to paths.pyc
byte-compiling build\bdist.win32\egg\asciimatics\renderers.py to renderers.pyc
byte-compiling build\bdist.win32\egg\asciimatics\scene.py to scene.pyc
byte-compiling build\bdist.win32\egg\asciimatics\screen.py to screen.pyc
byte-compiling build\bdist.win32\egg\asciimatics\sprites.py to sprites.pyc
byte-compiling build\bdist.win32\egg\asciimatics\version.py to version.pyc
byte-compiling build\bdist.win32\egg\asciimatics\widgets.py to widgets.pyc
byte-compiling build\bdist.win32\egg\asciimatics\__init__.py to __init__.pyc
creating build\bdist.win32\egg\EGG-INFO
copying asciimatics.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying asciimatics.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying asciimatics.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying asciimatics.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying asciimatics.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\asciimatics-1.7.3.dev0+ng0a21522.d20170209-py2.7.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing asciimatics-1.7.3.dev0+ng0a21522.d20170209-py2.7.egg
Copying asciimatics-1.7.3.dev0+ng0a21522.d20170209-py2.7.egg to c:\python27\lib\site-packages
Removing asciimatics 1.7.1.dev24+ngff13c2b.d20170209 from easy-install.pth file
Adding asciimatics 1.7.3.dev0+ng0a21522.d20170209 to easy-install.pth file

Installed c:\python27\lib\site-packages\asciimatics-1.7.3.dev0+ng0a21522.d20170209-py2.7.egg
Processing dependencies for asciimatics==1.7.3.dev0+ng0a21522.d20170209
Searching for pypiwin32==219
Best match: pypiwin32 219
Adding pypiwin32 219 to easy-install.pth file

Using c:\python27\lib\site-packages
Searching for future==0.16.0
Best match: future 0.16.0
Adding future 0.16.0 to easy-install.pth file
Installing pasteurize-script.py script to C:\Python27\Scripts
Installing pasteurize.exe script to C:\Python27\Scripts
Installing pasteurize.exe.manifest script to C:\Python27\Scripts
Installing futurize-script.py script to C:\Python27\Scripts
Installing futurize.exe script to C:\Python27\Scripts
Installing futurize.exe.manifest script to C:\Python27\Scripts

Using c:\python27\lib\site-packages
Searching for Pillow==3.0.0
Best match: Pillow 3.0.0
Processing pillow-3.0.0-py2.7-win32.egg
pillow 3.0.0 is already the active version in easy-install.pth
Installing enhancer.py script to C:\Python27\Scripts
Installing createfontdatachunk.py script to C:\Python27\Scripts
Installing gifmaker.py script to C:\Python27\Scripts
Installing pildriver.py script to C:\Python27\Scripts
Installing pilfile.py script to C:\Python27\Scripts
Installing explode.py script to C:\Python27\Scripts
Installing thresholder.py script to C:\Python27\Scripts
Installing viewer.py script to C:\Python27\Scripts
Installing painter.py script to C:\Python27\Scripts
Installing player.py script to C:\Python27\Scripts
Installing pilconvert.py script to C:\Python27\Scripts
Installing pilprint.py script to C:\Python27\Scripts
Installing pilfont.py script to C:\Python27\Scripts

Using c:\python27\lib\site-packages\pillow-3.0.0-py2.7-win32.egg
Searching for pyfiglet==0.7.5
Best match: pyfiglet 0.7.5
Adding pyfiglet 0.7.5 to easy-install.pth file
Installing pyfiglet-script.py script to C:\Python27\Scripts
Installing pyfiglet.exe script to C:\Python27\Scripts
Installing pyfiglet.exe.manifest script to C:\Python27\Scripts

Using c:\python27\lib\site-packages
Finished processing dependencies for asciimatics==1.7.3.dev0+ng0a21522.d20170209
```

**Comment by peterbrittain** [comment]
Now you have an issue with Pillow (which is a fork of PIL)...  The key is the last part of the exception trace:

>   File "C:\Python27\lib\site-packages\PIL\Image.py", line 512, in __getattr__
    raise AttributeError(name)
AttributeError: __exit__

It looks like it doesn't think Image is a context manager, but that's simply not true - the 3.0 branch in git shows the __exit__ function is present and correct.  Indeed, I've just tried running the 1.7.2 install with Pillow 3.0.0 and I don't see the error you.

I suggest you try uninstalling Pillow and re-installing it with pip (maybe to a later version?) and see what happens.  If that doesn't work, I think you need to try asking about it at https://github.com/python-pillow/Pillow
