### ISSUE TITLE
when i use cx_freeze to build it to an app, it raise error.

### ISSUE THREAD

**Issue by jekoie** [peterbrittain/asciimatics#87]
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "main.py", line 232, in <module>
  File "C:\Python27\lib\site-packages\asciimatics\screen.py", line 1021, in wrapper
    func(screen, *arguments)
  File "main.py", line 130, in kitty
  File "C:\Python27\lib\site-packages\asciimatics\renderers.py", line 284, in __init__
    self._images = [Figlet(font=font, width=200).renderText(text)]
  File "C:\Python27\lib\site-packages\pyfiglet\__init__.py", line 710, in __init__
    self.setFont()
  File "C:\Python27\lib\site-packages\pyfiglet\__init__.py", line 717, in setFont
    self.Font = FigletFont(font=self.font)
  File "C:\Python27\lib\site-packages\pyfiglet\__init__.py", line 90, in __init__
    self.data = self.preloadFont(font)
  File "C:\Python27\lib\site-packages\pyfiglet\__init__.py", line 100, in preloadFont
    if pkg_resources.resource_exists('pyfiglet.fonts', fn):
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1191, in resource_exists
    return get_provider(package_or_requirement).has_resource(resource_name)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 435, in get_provider
    __import__(moduleOrReq)
ImportError: No module named font
```

**Comment by peterbrittain** [comment]
This isn't a bug in asciimatics.  The problem is that you haven't packaged the pyfiglet font subdirectory with cx_freeze.  See https://stackoverflow.com/a/37026560/4994021 for more details of the problem.

Look at https://cx-freeze.readthedocs.io/en/latest/faq.html#problems-with-running-frozen-programs for details of how to include this dynamically loaded directory.
