### ISSUE TITLE
It raise TypeError when i use cx_freeze?

### ISSUE THREAD

**Issue by jekoie** [peterbrittain/asciimatics#96]
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "main.py", line 236, in <module>
  File "C:\Python27\lib\site-packages\asciimatics\screen.py", line 1021, in wrapper
    func(screen, *arguments)
  File "main.py", line 126, in kitty
  File "main.py", line 109, in __init__
  File "C:\Python27\lib\site-packages\asciimatics\widgets.py", line 268, in fix
    y = layout.fix(x, y, width, height)
  File "C:\Python27\lib\site-packages\asciimatics\widgets.py", line 821, in fix
    offset = max([0 if w.label is None else wcswidth(w.label) + 1 for w in column])
  File "D:\test\beauty\lovekitty\build\exe.win32-2.7\wcwidth\wcwidth.py", line 198, in wcswidth
    end = len(pwcs) if n is None else n
TypeError: object of type 'int' has no len()
```

**Comment by jekoie** [comment]
my code issue,sorry.
